

ISNORT := /opt/snort/include/snort
SNORT := /opt/snort/bin/snort
RELEASEDIR := $(abspath p/release)
DEBUGDIR := $(abspath p/debug)
MAKEDIR := $(abspath .m)


MODULE_NAME = trout_snort

DEBUG_MODULE := $(DEBUGDIR)/$(MODULE_NAME).so
RELEASE_MODULE := $(RELEASEDIR)/$(MODULE_NAME).so

.PHONY: format mkrtest premake postmake usage

usage:
	@echo Trout Snort plugins makefile instructions
	@echo 
	@echo To build a release build: make release
	@echo To build a debug build: make build
	@echo To clean all build folders: make clean
	@echo To run clang-format on all source files: make format

mkrtest: 
	@echo -------
	@echo debug: $(DEBUG_MODULE) release: $(RELEASE_MODULE)
	@echo Sub2: $(LIBDEFS)
	@echo deps: $(DEPS)
	@echo objs: $(OBJS)

test: $(DEBUG_MODULE)
	@echo Testing "$(TEST_DIRS)"
	cd sh3;go install
	sh3 -sanitize none -t $(DEBUG_MODULE) -tpath "$(TEST_DIRS)" $(TEST_LIMIT)

release-test: $(RELEASE_MODULE)
	@echo Testing "$(TEST_DIRS)"
	cd sh3;go install
	sh3 -sanitize none -t $(RELEASE_MODULE) -tpath "$(TEST_DIRS)" $(TEST_LIMIT)

#############################################

define README_CONTENT
  !!!Do NOT store any content you want to keep in this folder!!!

  The folder is automatically generated by the build process and all
  content in it will be deleted at random.
endef

MAKE_README_FILENAME := $(MAKEDIR)/README.TXT

clean:
	if [ -f $(DEBUG_MODULE) ]; then rm $(DEBUG_MODULE); fi
	if [ -f $(RELEASE_MODULE) ]; then rm $(RELEASE_MODULE); fi
	if [ -d $(MAKEDIR) ]; then rm -r $(MAKEDIR); fi
	@echo "\e[3;32mClean done\e[0m"

release: $(RELEASE_MODULE) | $(RELEASEDIR)
	@echo Result output to:  $(RELEASE_MODULE)
	@echo Release build done!

build: $(DEBUG_MODULE) | $(DEBUGDIR)
	@echo Result output to:  $(DEBUG_MODULE)
	@echo Debug build done!

gdb: $(DEBUG_MODULE)
	@echo "\e[3;37mStarting debugger...\e[0m"
	gdb --args $(SNORT) -v -c tests/test-local.lua --plugin-path $(DEBUGDIR) --pcap-dir pcaps --warn-all

format:
	clang-format -i $(CC_SOURCES) $(CC_HEADERS)

test-data: $(OUTPUTDIR)/$(MODULE)
	$(SNORT) -v -c test_config/cfg.lua --plugin-path $(DEBUGDIR) --pcap-dir test_data --warn-all

test-local: $(DEBUG_MODULE)
	$(SNORT) -v -c tests/test-local.lua --plugin-path $(DEBUGDIR) --pcap-dir pcaps --warn-all

$(MAKE_README_FILENAME): | $(MAKEDIR)
	$(file >$(MAKE_README_FILENAME),$(README_CONTENT))

$(MAKEDIR):
	mkdir -p $(MAKEDIR)


$(RELEASEDIR):
	mkdir -p $(RELEASEDIR)

$(DEBUGDIR):
	mkdir -p $(DEBUGDIR)

CC_SOURCES :=
CC_HEADERS :=
OBJS :=
DEPS :=
TEST_DIRS :=

########################################################################
# Reads FILES from all lib_def.mk files from all subfolders and adds 
# them with correct path to CC_SOURCES
define EXPAND_SOURCEFILES
 $(eval $(file <$(1)))
 SRC_DIR := $(dir $(1))
 ifdef CC_FILES
   CC_SOURCES += $(addprefix $$(SRC_DIR),$(CC_FILES))
   undefine CC_FILES
 endif
  
 ifdef H_FILES
   CC_HEADERS += $(addprefix $$(SRC_DIR),$(H_FILES))
   undefine H_FILES
 endif
 
 ifdef TEST_FOLDER
   TEST_DIRS := $(TEST_DIRS)$(addprefix $$(SRC_DIR),$(TEST_FOLDER));
   undefine TEST_FOLDER
 endif
  
endef

LIBDEFS = $(shell find $(SOURCEDIR) -name 'lib_def.mk')
$(foreach mk_file,$(LIBDEFS),$(eval $(call EXPAND_SOURCEFILES,$(mk_file))))
########################################################################

OBJS=$(abspath $(addprefix $(MAKEDIR)/, $(subst .cc,.o,$(CC_SOURCES))))
DEPS=$(abspath $(addprefix $(MAKEDIR)/, $(subst .cc,.d,$(CC_SOURCES))))

# Include dependencies if they exists
-include ${DEPS}

# Rule for how to compile .cc files to .o files
$(MAKEDIR)/%.o : %.cc | $(MAKE_README_FILENAME)
	@mkdir -p $(dir $@)
	g++ -MMD -MT '$(patsubst %.cc,$(MAKEDIR)/%.o,$<)' -pipe -O0 -std=c++2b -Wall -fPIC -Wextra -g -I $(ISNORT) -c $< -o $@

# Rule for linking debug build (how to generate $(OUTPUTDIR)/$(DEBUG_MODULE) )
$(DEBUG_MODULE): $(OBJS) | $(DEBUGDIR)
	@echo "\e[3;37mLinking...\e[0m"
	g++ $(OBJS) -shared -O0 -Wall -g -Wextra -o $(DEBUG_MODULE)

# Rule for linking release build (how to generate $(OUTPUTDIR)/$(RELEASE_MODULE) )
$(RELEASE_MODULE): $(CC_SOURCES) | $(RELEASEDIR)
	@echo "\e[3;37mLinking...\e[0m"
	g++ -O3 -std=c++2b -fPIC -Wall -Wextra -shared -I $(ISNORT) $(CC_SOURCES) -o $(RELEASE_MODULE)	

