#!/bin/sh
#
# Configure script generates the build files needed by Ninja for the project.
# It is run as part of redo release / redo debug, and usually not manually.
#
# for loops avoid creating a subshell
# shellcheck disable=SC2013

# This file should not include envrc, it will overwrite options given in the calling .do script
#. ./envrc

# Todo mkr - some cleanup needed, we add some flags to cxxflags and some to the command line (-MD -MF) others in the .do script, and some in envrc

cat << EOF
pd = $PD
cxxflags = $CXXFLAGS -Wall -Wextra -std=c++2b -fPIC -D_FORTIFY_SOURCE=2 -fstack-protector-strong -Werror=format-security
rule cc
  command = $CXX \$cxxflags -MD -MF \$out.d  -I $ID -isystem $INSTALL_DIR/include -isystem $INSTALL_DIR/include/snort -c \$in -o \$out
  deps = gcc
  depfile = \$out.d

rule lk
  command = $CXX -O -o \$out -shared \$in $LDFLAGS

build snort_plugins.o: cc $PD/snort_plugins.cc
EOF

final="build tm.so: lk snort_plugins.o "

link() { final="$final $1"; }

for m in $(cat plugins.list); do
	for f in $(cat "$PD/$m/files.list"); do
		echo "build $m/${f%.cc}.o: cc $PD/$m/$f"
		link "$m/${f%.cc}.o"
	done
done

echo "$final"
