redo-ifchange ../envrc snort_vars.rc

. ../envrc
. $TMP_FOLDER/snort_vars.rc

exec >&2

[ -d $BUILD_DIR ] || mkdir -p $BUILD_DIR

redo-ifchange libdaq_install libdaq_install_debug

(cd "$SNORT_SRC_DIR" || exit 1;
PKG_CONFIG_PATH="$INSTALL_DIR/lib/pkgconfig:$PKG_CONFIG_PATH" cmake \
  -S "$SNORT_SRC_DIR" \
  -B "$SNORT_BUILD_DIR" \
  -G Ninja \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCMAKE_INSTALL_PREFIX="$INSTALL_DIR" \
  -DCMAKE_BUILD_TYPE=Release \
  -DENABLE_STDLOG=ON \
  -DENABLE_LUAJIT_STATIC=OFF \
  -DENABLE_STATIC_DAQ=ON \
  -DDAQ_INCLUDE_PATH="$INSTALL_DIR/include" \
  -DDAQ_LIBRARIES_PATH="$INSTALL_DIR/lib" \
  -DCMAKE_C_COMPILER="$CC" \
  -DCMAKE_CXX_COMPILER="$CXX" \
  -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
  -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
  -DCMAKE_SHARED_LINKER_FLAGS="$LDFLAGS" \
  -DCMAKE_LINKER="$LD" )

(cd "$SNORT_SRC_DIR" || exit 1;
PKG_CONFIG_PATH="$INSTALL_DIR/lib/pkgconfig:$PKG_CONFIG_PATH" cmake \
  -S "$SNORT_SRC_DIR" \
  -B "$SNORT_BUILD_DIR_DEBUG" \
  -G Ninja \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCMAKE_INSTALL_PREFIX="$INSTALL_DEBUG_DIR" \
  -DCMAKE_BUILD_TYPE=Debug \
  -DENABLE_STDLOG=ON \
  -DENABLE_LUAJIT_STATIC=OFF \
  -DENABLE_STATIC_DAQ=ON \
  -DDAQ_INCLUDE_PATH="$INSTALL_DIR_DEBUG/include" \
  -DDAQ_LIBRARIES_PATH="$INSTALL_DIR_DEBUG/lib" \
  -DCMAKE_C_COMPILER="$CC" \
  -DCMAKE_CXX_COMPILER="$CXX" \
  -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
  -DCMAKE_EXE_LINKER_FLAGS="$LDFLAGS" \
  -DCMAKE_SHARED_LINKER_FLAGS="$LDFLAGS" \
  -DCMAKE_LINKER="$LD" )

redo-ifchange $(find $BASE_DIR/snort3 -type f )
redo-ifchange $SNORT_BUILD_DIR/build.ninja
redo-ifchange $SNORT_BUILD_DIR_DEBUG/build.ninja
