# Inspectors and spells are in place to attribute the correct flow
env BILL_PIPE=/tmp/llpipe_6808460440060963159
pcap $moddir/pcaps/google_http.pcap
grep '^N 10.67.21.59:48872 -> 209.85.202.100:80 http' flow.txt

-- cfg.lua --
stream = {}
stream_tcp = {}
http_inspect = {}
network_mapping = {pipe_env = "BILL_PIPE"}

wizard = {
    spells = { { service = 'http', proto = 'tcp', to_server = {'GET'}, to_client = {'HTTP/'} } }
}

binder = {
    { when = { service = 'http' }, use = { type = 'http_inspect' } },
    { use = { type = 'wizard' } }
}
