# Inspectors and spells are in place to attribute the correct flow
pcap testdata/google_http.pcap
cmp output.txt testdata/lioli_clear_test_txt.expected.txt

stdout 'clear_events: 4'
stdout 'did_clear: 2'

-- cfg.lua --

logger_file = { file_name = 'output.txt',
                serializer = 'serializer_txt' }

alert_lioli = { logger = 'logger_file',
                testmode = true }

stream = {}
stream_tcp = {}

ips = {
  include = 'lua.rules'
}

-- lua.rules --

log tcp any any -> any any (
  flags:S;
  lioli_clear;
  
  lioli_tag: $.tag "Tag test";

  lioli_tag: $.tag.nested "Nested ";
  lioli_tag: $.tag.nested "test";

  lioli_tag: $.principal.append "Append test";
  
  lioli_clear;

  lioli_tag: $.tag.clear "clear test";
  
  sid:3000000;
)
