pcap $moddir/pcaps/dhcp_clean.pcap
stdout '\[1\:100001\:0\] .* \(alerts\: 1\)'
stdout '\[1:100003:0] .* \(alerts\: 2\)'
stdout '\[1:100004:0] .* \(alerts\: 1\)'
stdout '\[8000:1010:0] .* \(alerts\: 5\)'


-- cfg.lua --
stream = { }
stream_udp = { }
dhcp = {
header_parsing=true
}

binder =
{
    { when = { proto = 'udp' }, use = { type = 'dhcp' }},
}

ips = {
  include = 'lua.rules'
}

-- lua.rules --

alert ip any 67 -> any 68 (
  msg:"DHCP option 3 spotted";
  dhcp_option:3;
  sid:100001;
)

alert ip any 67 -> any 68 (
  msg:"DHCP symbolic name test matches";
  dhcp_option:log_server;
  dhcp_option:netbios_over_TCP/IP_name_server;
  dhcp_option:5;
  dhcp_option:network_information_service+_domain;
  dhcp_option:simple_mail_transport_protocol_smtp_server;
  sid:100002;
)


alert ip any 67 -> any 68 (
  msg:"DHCP domain name match";
  dhcp_option:domain_name;
  content:"admin.acme.example.com";
  sid:100003;
)

alert ip any 67 -> any 68 (
  msg:"DHCP domain name match in offer";
  dhcp_option:15;
  content:"admin.acme.example.com";
  dhcp_option:53;
  byte_test:1, =, 2;
  sid:100004;
)


alert ip any any -> any any (
  msg:"Invalid dhcp packet";
  gid:8000;
  sid:1011;
)

alert ip any any -> any any (
  msg:"Valid dhcp packet";
  gid:8000;
  sid:1010;
)
