pcap testdata/udp_stream.pcap
cmp output.bill testdata/file_bill_expected.bill

-- cfg.lua --


stream = {}
stream_udp = {}

serializer_bill = { secret_sequence = '0123456789ABCDEF01' }


logger_file = {serializer = 'serializer_txt',
               file_name = 'output.bill'}

alert_lioli = { testmode = true,
                logger = 'logger_file'}


local_rules =
[[
log udp any any -> any any (
  msg: "This is a UDP stream";

  sid: 3002;
)
]]


ips = {
  rules = local_rules,
}





