pcap testdata/udp_stream.pcap
cmp output.lorth testdata/file_lorth_expected.lorth

-- cfg.lua --


stream = {}
stream_udp = {}

serializer_lorth = {}


logger_file = {serializer = 'serializer_lorth',
               file_name = 'output.lorth'}

alert_lioli = { testmode = true,
                logger = 'logger_file'}


local_rules =
[[
log udp any any -> any any (
  msg: "This is a UDP stream";

  sid: 3002;
)
]]


ips = {
  rules = local_rules,
}
