# Inspectors and spells are in place to attribute the correct flow
pcap $testdir/pcaps/google_http.pcap

# This test might not be valid, the files might be compared in text, rather than binary mode
cmp output.bill $testdir/alert_test_bill_no_dict.expected.bill

-- cfg.lua --
output_to_file = { file_name = 'output.bill' }
output_to_stdout = { }

log_bill =  { output = 'output_to_file',             
              option_generate_dictionary = false,
            }

alert_lioli = { logger = 'log_bill',
                testmode = true }

stream = {}
stream_tcp = {}
stream_udp = {}
http_inspect = {}

wizard = {
    spells = { { service = 'http', proto = 'tcp', to_server = {'GET'}, to_client = {'HTTP/'} } }
}

binder = {
    { when = { service = 'http' }, use = { type = 'http_inspect' } },
    { use = { type = 'wizard' } }
}

ips = {
  include = 'lua.rules'
}

-- lua.rules --

alert ip any any -> any any (
  msg:"This is a log of an http header";

  http_header:field host;
  lioli_bind:host;
  content:"google";

  http_method;
  lioli_bind:method;
)
