pcap -expect-fail $testdir/pcaps/google_http.pcap

stderr 'invalid argument lioli_tag: = invalid "path needs to start with \$."'
stderr 'invalid argument lioli_tag: = \$.invalid-path "'
stderr 'FATAL: see prior 5 errors'

-- cfg.lua --

logger_null = { }

alert_lioli = { logger = 'logger_null',
                testmode = true }

stream = {}
stream_tcp = {}
stream_udp = {}
http_inspect = {}

wizard = {
    spells = { { service = 'http', proto = 'tcp', to_server = {'GET'}, to_client = {'HTTP/'} } }
}

binder = {
    { when = { service = 'http' }, use = { type = 'http_inspect' } },
    { use = { type = 'wizard' } }
}

ips = {
  include = 'lua.rules'
}

-- lua.rules --

alert ip any any -> any any (
  msg:"This is a log of an http header";
  
  lioli_tag; 
  lioli_tag: invalid "path needs to start with $.";
  lioli_tag: $.invalid-path "'-' are not allowed in paths";
)
