# This file was autogenerated by running "make wizard/envrc.do" from the project root folder

cat << EOF > $3
# NOTE: This configuration will use the debug version of the plugins, and might use a debug version of snort
SNORT="/home/mike/code/snort-modules/deps/dev/bin/snort"
SNORT_PLUGIN_PATH="/home/mike/code/snort-modules/p/debug"
SNORT_DAQ_INCLUDE_OPTION="--daq-dir /home/mike/code/snort-modules/deps/dev/lib/daq "
EOF
