#set document(title: [TroutSoftware/netsniffer — Build & Test Reference])
 
== Overview
netsniffer is a set of Snort 3 plugins and rules.
All compilation happens inside a controlled build (Alpine Linux-based) environment.
The build orchestrator is redo (a dependency-driven shell script build system).
Redo drives a Ninja build for the C/C++ compilation, and handles bootstrapping the Alpine sandbox, configuring the compiler toolchain, and running tests.

== Alpine Bootstrap Environment
The project ships a Bubblewrap-based sandbox under `test_envr_alpn/`.
Two entry-point scripts cover the two common development modes:
 - `test_envr_alpn/bshell.sh`: Standard development shell. On first run, downloads Alpine Linux and builds the image. Drops the developer into an Alpine prompt with the repository bind-mounted. All normal redo targets are available.
 - `test_envr_alpn/bshell_capture.sh`: Promiscuous-mode variant. Launched with sudo on the host to grant network access. Snort can be run against a live interface from this prompt.

The envrc.do redo script generates a sourced environment file.
It enforces that the build is running on Alpine (/etc/alpine-release must exist), then exports the full compiler toolchain: CC=clang, CXX=clang++, LD=ld.lld, plus LLVM archiver and strip utilities from /usr/lib/llvm21/bin.
A USE_LLVM_CXX_LIB flag (default: 0) switches between libstdc++ and libc++/libc++abi, adjusting LDFLAGS and CXXFLAGS accordingly.

== libdaq and Snort Check-in Strategy

libdaq and Snort 3 are vendored directly into the repository (under the daq/ directory for libdaq and the main core/ tree for Snort) rather than being fetched at build time from upstream.
This makes the build self-contained and reproducible — no network access to third-party package repositories is required once the Alpine image is present.

The redo targets build_scripts/snort_install and build_scripts/snort_install_debug drive the build and install of Snort and libdaq into the local prefix trees p/install (release) and p/install_debug (debug), referenced by the INSTALL_DIR and INSTALL_DEBUG_DIR environment variables. 

Outputs land at:

```
p/install/bin/snort        release binary
p/install/lib/             release libdaq
p/install_debug/bin/snort  debug binary
p/install_debug/lib/       debug libdaq
```

The snort.sh, snort-release.sh, and snort-gdb.sh wrapper scripts ensure LD_LIBRARY_PATH is set correctly so the vendored libdaq is picked up instead of any system library.

== Build Options

Ninja build files are generated by ninja_configure.do. Both release and debug build directories (p/release / p/debug) are configured in one pass. The compiler flags differ:

#table(columns: 3,
[Target], [Command], [Notes],
[Production release], [`redo release`], [Flags: `-O2`. Output: p/release/tm.so],
[Debug build], [`redo debug`], [Flags: -Og -g. Output: p/debug/tm.so], 
[Full test suite], [`redo test`], [Builds release, then runs Go + sh3 tests],
[LLDB session], [`./lldb.sh [snort args]`], [Builds debug, launches LLDB with C++ exception breakpoint],
)

Compiler flags
All builds share -Wall -Wextra -Werror -Wpedantic -pedantic-errors and -fPIC. The compiler is always clang/clang++ from LLVM 21, with ld.lld as the linker. By default the build links libstdc++; setting USE_LLVM_CXX_LIB=1 in the environment switches to libc++ with compiler-rt and libunwind.

== Testing
Tests are driven by test.do. Running redo test sequentially: (1) ensures the release build is current, (2) runs Go unit tests across all packages with go test ./..., and (3) executes sh3 integration tests.

== sh3 integration tests

sh3 (go tool sh3) is a test runner that exercises Snort plugins end-to-end against captured pcap data. Test entry points are listed in sh3_tests.list, one module name per line (comments prefixed with \#). Each listed module must provide a files.list enumerating its source files. Modules are tested from the `sh3_tests.list`.

== LLDB debugging

The lldb.sh wrapper builds the debug variant and launches LLDB pre-configured with:
    - Target: p/install_debug/bin/snort
    - Plugin: p/debug/tm.so loaded via --plugin-path
    - Auto-breakpoint: C++ exceptions (breakpoint set -E c++) — useful for catching plugin crashes before the backtrace is lost.
    - Extra args: pass additional Snort flags directly to the script (forwarded as \$@).
