# Inspectors and spells are in place to attribute the correct flow
pcap $testdir/pcaps/google_http.pcap
cmp output.lorth $testdir/netflow_test.expected.lorth 

-- cfg.lua --
logger_file = { file_name = 'output.lorth',
                serializer = 'serializer_lorth' }

trout_netflow = { logger = 'logger_file',
                  testmode = true } 

stream = {}
stream_tcp = {}
stream_udp = {}
http_inspect = {}

wizard = {
    spells = { { service = 'http', proto = 'tcp', to_server = {'GET'}, to_client = {'HTTP/'} } }
}

binder = {
    { when = { service = 'http' }, use = { type = 'http_inspect' } },
    { use = { type = 'wizard' } }
}

