name: execute tests
on: [push]
jobs:
  execute_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
      - run: sh ./install_deps
      - run: sh ./bootstrap/do
      - name: archive build logs
        uses: actions/upload-artifact@v4
        with:
          name: snort_build_log
          path: bootstrap/snort_install_log
